# Generated by Django 5.2.7 on 2025-10-27 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(default='student@gmail.com', max_length=50)),
                ('stu_mobile', models.CharField(help_text='Enter a valid 10-digit mobile number starting with 6-9.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits and start with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')])),
            ],
        ),
    ]
