# Generated by Django 5.2.7 on 2025-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='profile_pic',
            field=models.URLField(default='empty'),
        ),
    ]
